name = "surfing-latam"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "public"

[assets]
directory = "./public"
binding = "ASSETS"

[ai]
binding = "AI"
